language: php

services:
  - docker

php:
  - '7.0'

install:
  - composer install
  - mkdir -p build/logs
  - docker run --name mariadb -e MYSQL_ROOT_PASSWORD= -e MYSQL_DATABASE=travis -d mariadb:latest
  - docker build -t pwred/vrata .
  - docker run -d pwred/vrata --link mariadb:mariadb --name app -e DB_HOST=mariadb -e APP_KEY=EzMx2svtA1CsOzPrqE9EMmUkegls4mjv -e DB_DATABASE=travis -e DB_USERNAME=root -e APP_ENV=testing; sleep 10

script:
  - docker run pwred/vrata /bin/sh -c "cd /home/app; env; php artisan migrate"
  - docker run pwred/vrata /bin/sh -c "cd /home/app; ./vendor/bin/phpunit"
  - docker run pwred/vrata /bin/sh -c "cd /home/app; ./vendor/bin/test-reporter"

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker commit app pwred/vrata
  - docker push pwred/vrata