language: php

services:
  - mysql

env:
  - DB_USERNAME="root" DB_HOST="127.0.0.1" DB_PASSWORD="" DB_DATABASE="travis" APP_ENV="testing"

php:
  - '7.0'

before_script:
  - composer install --dev
  - mysql -e 'create database travis;'
  - php artisan migrate
