language: php

services:
  - mysql
  - docker

env:
  - DB_USERNAME="root" DB_HOST="127.0.0.1" DB_PASSWORD="" DB_DATABASE="travis" APP_ENV="testing" APP_KEY="Idgz1PE3zO9iNc0E3oeH3CHDPX9MzZe4"

php:
  - '7.0'

install:
  - composer install
  - mkdir -p build/logs
  - mysql -e 'create database travis;'
  - docker build -t pwred/vrata .
  - docker run -d pwred/vrata --name app; sleep 10

script:
  - docker run app /bin/sh -c "cd /home/app; export DB_HOST=127.0.0.1 && export DB_DATABASE=travis && export DB_USERNAME=root && export APP_ENV=testing; php artisan migrate"
  - docker run app /bin/sh -c "cd /home/app; export DB_HOST=127.0.0.1 && export APP_KEY=EzMx2svtA1CsOzPrqE9EMmUkegls4mjv && export DB_DATABASE=travis && export DB_USERNAME=root && export APP_ENV=testing; ./vendor/bin/phpunit"
  - docker run app /bin/sh -c "cd /home/app; ./vendor/bin/test-reporter"

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker commit app pwred/vrata
  - docker push pwred/vrata