language: php

services:
  - mysql
  - docker

env:
  - DB_USERNAME="root" DB_HOST="127.0.0.1" DB_PASSWORD="" DB_DATABASE="travis" APP_ENV="testing" APP_KEY="Idgz1PE3zO9iNc0E3oeH3CHDPX9MzZe4"

php:
  - '7.0'

install:
  - composer install

after_install:
  - mkdir -p build/logs
  - mysql -e 'create database travis;'
  - docker build -t pwred/vrata .
  - docker run -d pwred/vrata

script:
  - docker run pwred/vrata /bin/sh -c "cd /home/app; ./vendor/bin/phpunit"
  - docker run pwred/vrata /bin/sh -c "cd /home/app; ./vendor/bin/test-reporter"

deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push pwred/vrata